name: glub
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/cosmopool/glub

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
